const docs = [
  ["Public release handoff", "PUBLIC_RELEASE_HANDOFF.md"],
  ["Feature classification", "FEATURE_CLASSIFICATION.md"],
  ["Extraction map", "EXTRACTION_MAP.md"],
  ["Sanitization checklist", "SANITIZATION_CHECKLIST.md"],
  ["Public MVP roadmap", "PUBLIC_MVP_ROADMAP.md"],
  ["Repo separation rules", "REPO_SEPARATION_RULES.md"],
  ["Extraction readiness assessment", "EXTRACTION_READINESS_ASSESSMENT.md"],
  ["Layer 1 app frame status", "LAYER_1_APP_FRAME_STATUS.md"],
  ["Layer 2 chat/model config status", "LAYER_2_CHAT_MODEL_CONFIG_STATUS.md"],
  ["Layer 3 workstation and command center status", "LAYER_3_WORKSTATION_COMMAND_CENTER_STATUS.md"],
  ["Layer 4 Round Table static flow status", "LAYER_4_ROUNDTABLE_STATIC_FLOW_STATUS.md"],
  ["Layer 5 memory/context adapter status", "LAYER_5_MEMORY_CONTEXT_ADAPTER_STATUS.md"],
  ["Layer 6 Task Guardian health status", "LAYER_6_TASK_GUARDIAN_HEALTH_STATUS.md"],
] as const;

const repoDocsBase =
  "https://github.com/armpit-symphony/Sparkbot_shell/blob/public-release-layer-6-task-guardian-health-shell/docs";

export function DocsPage() {
  return (
    <section className="page-section">
      <div className="intro-row">
        <div>
          <p className="section-label">Docs</p>
          <h2>Public shell planning references</h2>
          <p>
            These docs define what is public, what stays private, and what must be validated before
            later runtime imports.
          </p>
        </div>
        <aside className="status-card">
          <span>Status</span>
          <strong>Repo docs only; no runtime docs are generated by the app.</strong>
        </aside>
      </div>

      <div className="docs-list">
        {docs.map(([label, fileName]) => (
          <a href={`${repoDocsBase}/${fileName}`} key={fileName}>
            <span>{label}</span>
            <small>{`docs/${fileName}`}</small>
          </a>
        ))}
      </div>

      <div className="runtime-boundary">
        <strong>Documentation boundary</strong>
        <p>
          Layer 6 links repo Markdown planning files only. It does not include internal R&D notes,
          package artifacts, secrets, tests, workflows, or private deployment instructions.
        </p>
      </div>
    </section>
  );
}
